### ISSUE TITLE
Linter JS errors

### ISSUE THREAD

**Issue by onetrev** [mikaeljorhult/brackets-php-code-quality-tools#19]
If I have anything other than PHP Lint turned on, on Brackets console starts throwing these errors any time it runs. Any ideas what might be causing this? Thanks!!

```
Exception in 'change' listener on PrefixedPreferencesSystem TypeError: undefined is not a function TypeError: undefined is not a function
    at Parser.PHPCS.prepareStandards (file:///C:/Users/Trevor/AppData/Roaming/Brackets/extensions/user/mikaeljorhult.brackets-php-lint-tools/modules/parsers/phpcs.js:28:32)
    at Parser.PHPCS.buildCommand (file:///C:/Users/Trevor/AppData/Roaming/Brackets/extensions/user/mikaeljorhult.brackets-php-lint-tools/modules/parsers/phpcs.js:12:47)
    at Parser.parse (file:///C:/Users/Trevor/AppData/Roaming/Brackets/extensions/user/mikaeljorhult.brackets-php-lint-tools/modules/parsers/base.js:32:19)
    at getErrors (file:///C:/Users/Trevor/AppData/Roaming/Brackets/extensions/user/mikaeljorhult.brackets-php-lint-tools/modules/ParserManager.js:39:23)
    at getErrorsFromDocument (file:///C:/Users/Trevor/AppData/Roaming/Brackets/extensions/user/mikaeljorhult.brackets-php-lint-tools/modules/ParserManager.js:118:4)
    at getErrorsFromEditor (file:///C:/Users/Trevor/AppData/Roaming/Brackets/extensions/user/mikaeljorhult.brackets-php-lint-tools/modules/ParserManager.js:111:4)
    at file:///C:/Users/Trevor/AppData/Roaming/Brackets/extensions/user/mikaeljorhult.brackets-php-lint-tools/modules/ParserManager.js:100:6
    at Object.trigger (/utils/EventDispatcher.js:222:40)
    at eval (/preferences/PreferencesBase.js:1122:26)
    at PreferencesSystem.trigger (/utils/EventDispatcher.js:222:40)
```

**Comment by mikaeljorhult** [comment]
Which version of Brackets are you using?

**Comment by onetrev** [comment]
I'm on the latest version, Release 1.2 build 1.2.0-15697, Windows 8.1.

**Comment by mikaeljorhult** [comment]
I'm unable to recreate this problem. Please try the extension with the latest version of Brackets.
