### ISSUE TITLE
No detected errors and warnings are being shown in the lint pane

### ISSUE THREAD

**Issue by cithukyaw** [mikaeljorhult/brackets-php-code-quality-tools#22]
I installed the version 0.1.7 (latest version at the time of this writing) in Brackets 1.3 and Windows 7. I think it would work upon file save, but It seems not working. I have `php` in PATH. The extension settings are all default. The menu **View -> Lint Files on Save** is checked.

I have CodeSniffer installed globally. I found that this extension is shipped with a standalone `phpcs.phar`. I think it is not a problem since both could be run successfully in CLI.

```
C:\>phpcs --version
PHP_CodeSniffer version 2.0.0 (stable) by Squiz (http://www.squiz.net)
```
```
C:\~\Brackets\extensions\user\mikaeljorhult.brackets-php-lint-tools\modules\vendor\phpcs>php php
cs.phar --version
PHP_CodeSniffer version 2.0.0a3 (alpha) by Squiz (http://www.squiz.net)
```

Running `phpcs` in CLI is working for both `phpcs` or `php phpcs.phar`. I got several CodeSniffer warnings and errors for my file.
```
C:\>phpcs path\to\file.php`
..... errors and warnings shown here
......
C:\~\Brackets\extensions\user\mikaeljorhult.brackets-php-lint-tools\modules\vendor\phpcs>php phpcs.phar path\to\file.php`
..... errors and warnings shown here
......
```

I found that "**No linter available for PHP**" in the right bottom corner of IDE. Formerly I used the extension [PHPLint](https://github.com/DoersGuild/brackets-phplint) by Sathvik and it worked. I removed it when I installed this code quality tool to avoid conflict.

**Comment by cithukyaw** [comment]
In IDE developer console (F12), I found an error whenever a file is open.
> [brackets-editorconfig] failed to parse configuration Max connection attempts reached at main.js:165

I removed the "EditorConfig" extension and then no more error at main.js:165. However it could not solve the original issue.

**Comment by mikaeljorhult** [comment]
That's weird. I run version 0.1.7 with Brackets 1.3 on both Windows and Mac OS X without any problems. Do you have any other extensions installed?

**Comment by cithukyaw** [comment]
I tried to disable and enable each extension one by one. I found two extensions that could break your extension to work.

(1) When [funcdocr](https://github.com/wikunia/brackets-funcdocr) is installed and enabled, "Errors: 1" is shown in the status bar. In the developer console, I found these

```
Exception when calling a 'brackets done loading' handler: TypeError: undefined is not a function
/utils/AppInit.js:96 TypeError: undefined is not a function
    at Parser.PHPCS.prepareStandards (file:///C:/Users/TPP/AppData/Roaming/Brackets/extensions/user/mikaeljorhult.brackets-php-lint-tools/modules/parsers/phpcs.js:28:32)
    at Parser.PHPCS.buildCommand (file:///C:/Users/TPP/AppData/Roaming/Brackets/extensions/user/mikaeljorhult.brackets-php-lint-tools/modules/parsers/phpcs.js:12:47)
    at Parser.parse (file:///C:/Users/TPP/AppData/Roaming/Brackets/extensions/user/mikaeljorhult.brackets-php-lint-tools/modules/parsers/base.js:32:19)
    at getErrors (file:///C:/Users/TPP/AppData/Roaming/Brackets/extensions/user/mikaeljorhult.brackets-php-lint-tools/modules/ParserManager.js:39:23)
    at getErrorsFromDocument (file:///C:/Users/TPP/AppData/Roaming/Brackets/extensions/user/mikaeljorhult.brackets-php-lint-tools/modules/ParserManager.js:118:4)
    at getErrorsFromEditor (file:///C:/Users/TPP/AppData/Roaming/Brackets/extensions/user/mikaeljorhult.brackets-php-lint-tools/modules/ParserManager.js:111:4)
    at _callHandler (/utils/AppInit.js:93:13)
    at _addListener (/utils/AppInit.js:128:13)
    at Object.appReady (/utils/AppInit.js:141:9)
    at NodeConnection.<anonymous> (file:///C:/Users/TPP/AppData/Roaming/Brackets/extensions/user/mikaeljorhult.brackets-php-lint-tools/modules/ParserManager.js:96:13)	
```
(2) When [JSCS for Brackets](https://github.com/globexdesigns/brackets-jscs) is installed and enabled, I found the following errors in the developer console. It seems stopping node server unexpectedly. This could cause your extension boken.

![635682783052642734](https://cloud.githubusercontent.com/assets/4285555/7817562/d212dd48-03fb-11e5-8569-f75895a89516.png)


I'm not sure No (2) is related to this extension issue. If not, I will submit an issue to that extension "JSCS". If those two extensions are disabled, your extension is working fine.

**Comment by mikaeljorhult** [comment]
The JSCS seem to indeed stop the Node server which would cause my extension to be unable to call the any terminal commands. That needs to be addressed by that author.

I'll look into the first error though to see what's causing it.

**Comment by cithukyaw** [comment]
Okay. Thank you. By the way, how can I use a custom rule set for phpcs in this extension?

**Comment by mikaeljorhult** [comment]
It's not possible at this time. It's in the backlog though.

**Comment by mikaeljorhult** [comment]
Resolved with a new version of JSCS.
